# Generated by Django 3.1.3 on 2021-04-29 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0003_auto_20210429_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='followers',
        ),
    ]
